name: ServerRestart
version: 1.0.0
main: com.example.serverrestart.ServerRestart
api-version: '1.13'
description: A plugin for restarting the server with a countdown
author: TimLuist

commands:
  resta:
    description: Restart the server with a countdown or stop a restart
    usage: /resta [reason], /resta stop, or /resta help
    permission: serverrestart.use
    permission-message: You don't have permission to use this command

permissions:
  serverrestart.use:
    description: Allows use of the restart command
    default: op
  serverrestart.stop:
    description: Allows stopping a restart countdown
    default: op
  serverrestart.*:
    description: Grants all ServerRestart permissions
    default: op
    children:
      serverrestart.use: true
      serverrestart.stop: true
