name: ServerRestart
version: 1.0.0
main: com.example.serverrestart.ServerRestart
api-version: '1.21'
description: A plugin for restarting the server with a countdown
author: YourName

commands:
  resta:
    description: Restart the server with a countdown or stop a restart
    usage: /resta, /resta stop, or /resta help
    permission: serverrestart.use
    permission-message: You don't have permission to use this command

permissions:
  serverrestart.use:
    description: Allows use of the restart command
    default: op
